consumidores: 2
produtores_voz: 3
produtores_email: 3
produtores_chat: 3
produtores_timeout: 10
DB:
- driver: org.h2.Driver
  url: jdbc:h2:mem:test
  hibernate_dialect: org.hibernate.dialect.H2Dialect
  hibernate_hbm2ddl_auto: create-drop
  usuario: sa
  senha: ""